import { Josefin_Sans } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from "./Layout.module.css";
import currentLocation from "./data";
import { renderComponent } from "./utils/renderComponent";
import { ThemeProvider } from './context/ThemeContext';

const josefinSans = Josefin_Sans({
  weight: ['400','500', '600','700',], // Specify the weights you need
  subsets: ['latin'], // Optional: specify subsets
  display: 'swap', // Optional: font display strategy
  variable: '--font-josefin-sans' // Set a CSS variable for the font
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const location = currentLocation;
  const shared = currentLocation.shared || {};

  return (
    <html lang="en">
      <ThemeProvider>
        <body className={josefinSans.variable}>
          {shared &&
            renderComponent({
              component: shared.header.name,
              media: location.media,
              src: shared.header.src,
              name: location.name,
              menuItems : shared.header.menuItems,
              button: shared.header.button
            })
          }
          <main>{children}</main>
          <div className={styles.footerContaner}>
            {shared &&
              renderComponent({
                component: shared.footer.name,
                src: shared.footer.src,
                refersrc: shared.footer.refersrc,
                title: location.title,
                footerRights:shared.footer.footerRights,
                data:shared.footer.data
              })
            }
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
